# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0002_auto_20170722_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
