# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item_condition',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='item_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='item_photo',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='item_type',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='item_use',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
