# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0004_auto_20170724_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
