# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0008_auto_20170726_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
