# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0011_auto_20170726_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
    ]
