# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0013_post_item_condition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_condition_slug',
            field=autoslug.fields.AutoSlugField(default='brand-new', editable=False, populate_from='item_condition'),
        ),
    ]
