# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 09:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0020_auto_20170812_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='exchange_offer',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='user_id', chained_model_field='user_id', default=7, on_delete=django.db.models.deletion.CASCADE, to='newbeginnings.Post'),
        ),
    ]
