# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbeginnings', '0023_auto_20170812_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
